(() => {
  if (!window.location.search.includes("test=1")) return;

  function getSnapshot() {
    const game = window.DalgaSavunmasiGame;
    const state = game.state;
    const screen = window.ShooterCamera.toScreen(state.camera, state.player);
    const evolution = window.WeaponEvolution.getWeaponEvolution(state.player);
    const relicSynergies = window.RelicSynergy?.getActiveSynergies?.(state.player) || [];
    const itemSynergies = window.RunItemSystem?.getActiveSynergies?.(state.player) || [];
    return {
      phase: state.phase,
      trailColor: state.trailColor,
      lives: state.player.lives,
      score: state.score,
      wave: state.wave,
      level: state.level,
      xp: state.xp,
      x: Math.round(state.player.x),
      y: Math.round(state.player.y),
      cameraX: Math.round(state.camera.x),
      cameraY: Math.round(state.camera.y),
      screenX: Math.round(screen.x),
      screenY: Math.round(screen.y),
      viewWidth: game.viewport.width,
      viewHeight: game.viewport.height,
      worldWidth: game.world.width,
      worldHeight: game.world.height,
      title: document.querySelector("#phaseTitle").textContent,
      overlayHidden: document.querySelector("#overlay").classList.contains("is-hidden"),
      shake: state.shake,
      flashEnemies: state.impactFlashes.length + state.enemies.filter((enemy) => enemy.flash > 0).length,
      particles: state.particles.length,
      bullets: state.bullets.length,
      enemyBullets: state.enemyBullets.length,
      bossTelegraphs: (state.bossTelegraphs || []).length,
      bossPhaseFlashes: (state.bossPhaseFlashes || []).length,
      shotsFired: state.shotsFired,
      hordeEnemies: state.enemies.length,
      enemyTypes: [...new Set(state.enemies.map((enemy) => enemy.type))].sort().join(","),
      formations: [...new Set(state.enemies.filter((enemy) => enemy.formationId).map((enemy) => enemy.formationId))].length,
      captains: state.enemies.filter((enemy) => enemy.captain).length,
      captainBuffedEnemies: state.enemies.filter((enemy) => enemy.captainBuff).length,
      lastFormation: state.lastFormation?.type || "",
      bosses: state.enemies.filter((enemy) => enemy.type === "boss").length,
      eliteEnemies: state.enemies.filter((enemy) => enemy.elite).length,
      eliteAffixes: [...new Set(state.enemies.filter((enemy) => enemy.elite).map((enemy) => enemy.affix))].sort().join(","),
      lootItems: (state.lootDrops || []).length,
      lootTypes: [...new Set((state.lootDrops || []).map((loot) => loot.type))].sort().join(","),
      shields: state.player.shields || 0,
      overdriveActive: (state.player.overdrive || 0) > 0,
      overdriveCharge: Math.round(state.player.overdriveCharge || 0),
      overdriveReady: Boolean(state.player.overdriveReady),
      overdriveMode: window.OverdriveSystem?.getMode?.(state.player).id || "",
      overdriveBursts: (state.overdriveBursts || []).length,
      overdriveTime: Number((state.player.overdrive || 0).toFixed(2)),
      lootCores: state.player.lootCores || 0,
      relicChoices: state.relicChoices.length,
      relicCount: (state.player.relics || []).length,
      relicFields: (state.relicFields || []).length,
      relicRevealActive: state.phase === "relicReveal",
      relicRevealBursts: (state.relicRevealBursts || []).length,
      relicSynergies: relicSynergies.map((synergy) => synergy.id).join(","),
      bossArchetypes: [...new Set(state.enemies.filter((enemy) => enemy.type === "boss").map((enemy) => enemy.bossArchetype))].sort().join(","),
      lastBossReward: state.lastBossReward?.archetype || "",
      lastBossAttackPattern: state.lastBossAttackPattern || "",
      lastBossTelegraphPattern: state.lastBossTelegraphPattern || "",
      lastBossPhase: state.lastBossPhaseChange?.phase || 0,
      mountedWeapons: window.SurvivalRules.getMountedWeaponCount(state.player),
      plasmaBullets: state.bullets.filter((bullet) => bullet.style === "plasma").length,
      weaponEvolution: evolution.id,
      weaponSynergies: evolution.synergies.join(","),
      twinPlasmaBullets: state.bullets.filter((bullet) => bullet.style === "twinPlasma").length,
      piercingBullets: state.bullets.filter((bullet) => bullet.style === "piercingLaser").length,
      droneBullets: state.bullets.filter((bullet) => bullet.origin === "drone").length,
      coreDroneBullets: state.bullets.filter((bullet) => bullet.origin === "coreDrone").length,
      burningEnemies: state.enemies.filter((enemy) => (enemy.burnTime || 0) > 0).length,
      chainArcs: (state.chainArcs || []).length,
      sectorEvent: state.sector?.activeEvent?.type || "",
      threatLabel: state.spawnDirector?.lastDifficulty?.threatLabel || "",
      enemyCap: state.spawnDirector?.lastDifficulty?.enemyCap || 0,
      spawnInterval: state.spawnDirector?.lastDifficulty?.spawnInterval || 0,
      swarmWave: Boolean(state.spawnDirector?.lastDifficulty?.swarmWave),
      bossTier: state.enemies.find((enemy) => enemy.type === "boss")?.bossTier || state.spawnDirector?.lastDifficulty?.bossTier || "",
      landmarkZone: state.landmarkState?.activeZone?.id || "",
      landmarks: state.landmarkState?.landmarks?.length || 0,
      landmarkRewardCharge: Number((state.landmarkState?.rewardCharge || 0).toFixed(2)),
      missionTitle: state.mission?.active?.title || "",
      missionProgress: state.mission?.active ? `${Math.floor(state.mission.active.progress)}/${state.mission.active.target}` : "",
      completedMissions: state.mission?.completed || 0,
      objectiveKind: state.tacticalObjectives?.active?.kind || "",
      objectiveTitle: state.tacticalObjectives?.active?.title || "",
      objectiveProgress: state.tacticalObjectives?.active
        ? `${Math.floor(state.tacticalObjectives.active.progress)}/${state.tacticalObjectives.active.target}`
        : "",
      objectiveCompleted: state.tacticalObjectives?.completed || 0,
      objectiveLastReward: state.tacticalObjectives?.lastCompleted?.kind || "",
      objectivePointer: window.CombatUx?.getObjectivePointer?.(state, game.viewport)?.title || "",
      overdrivePrompt: window.CombatUx?.getOverdrivePrompt?.(state)?.title || "",
      uxNotices: (state.uxNotices || []).length,
      challengeHazards: state.enemyBullets.filter((bullet) => ["ionBolt", "meteor", "plasmaWall", "riftMine"].includes(bullet.style)).length,
      ionBolts: state.enemyBullets.filter((bullet) => bullet.style === "ionBolt").length,
      meteors: state.enemyBullets.filter((bullet) => bullet.style === "meteor").length,
      plasmaWalls: state.enemyBullets.filter((bullet) => bullet.style === "plasmaWall").length,
      riftMines: state.enemyBullets.filter((bullet) => bullet.style === "riftMine").length,
      pierceRemaining: state.bullets.reduce((total, bullet) => total + (bullet.pierceLeft || 0), 0),
      itemPoolSize: window.RunItemSystem?.getItemPool?.().length || 0,
      itemSynergies: itemSynergies.map((synergy) => synergy.id).join(","),
      ownedItemCount: state.player.itemState?.ownedIds?.length || 0,
      ownedItems: (state.player.itemState?.ownedIds || []).join(","),
      selectedItemCount: state.itemSelection?.selectedIds?.length || 0,
      upgradeChoices: state.upgradeChoices.length,
      upgradeChoiceTypes: state.upgradeChoices.map((choice) => choice.choiceType || "stat").join(","),
      upgradeCount: state.player.upgrades.length,
      spaceObjects: state.spaceObjects.length,
      starLayers: new Set(state.stars.map((star) => star.layer)).size,
    };
  }

  window.DalgaSavunmasiTest = {
    chooseUpgrade: window.DalgaSavunmasiGame.chooseUpgrade,
    activateOverdrive: window.DalgaSavunmasiGame.activateOverdrive,
    endGame: window.DalgaSavunmasiGame.endGame,
    finishWave: window.DalgaSavunmasiGame.finishWave,
    forceBoss: window.DalgaSavunmasiGame.forceBoss,
    grantXp: window.DalgaSavunmasiGame.grantXp,
    hitFirstEnemy: window.DalgaSavunmasiGame.hitFirstEnemy,
    hitPlayer: window.DalgaSavunmasiGame.hitPlayer,
    snapshot: getSnapshot,
    start: window.DalgaSavunmasiGame.start,
    startPlaying: window.DalgaSavunmasiGame.startPlaying,
  };
})();
