(() => {
  if (!window.location.search.includes("test=1")) return;

  function getSnapshot() {
    const game = window.DalgaSavunmasiGame;
    const state = game.state;
    const screen = window.ShooterCamera.toScreen(state.camera, state.player);
    const evolution = window.WeaponEvolution.getWeaponEvolution(state.player);
    const relicSynergies = window.RelicSynergy?.getActiveSynergies?.(state.player) || [];
    return {
      phase: state.phase,
      trailColor: state.trailColor,
      lives: state.player.lives,
      score: state.score,
      wave: state.wave,
      level: state.level,
      xp: state.xp,
      x: Math.round(state.player.x),
      y: Math.round(state.player.y),
      cameraX: Math.round(state.camera.x),
      cameraY: Math.round(state.camera.y),
      screenX: Math.round(screen.x),
      screenY: Math.round(screen.y),
      viewWidth: game.viewport.width,
      viewHeight: game.viewport.height,
      worldWidth: game.world.width,
      worldHeight: game.world.height,
      title: document.querySelector("#phaseTitle").textContent,
      overlayHidden: document.querySelector("#overlay").classList.contains("is-hidden"),
      shake: state.shake,
      flashEnemies: state.impactFlashes.length + state.enemies.filter((enemy) => enemy.flash > 0).length,
      particles: state.particles.length,
      bullets: state.bullets.length,
      enemyBullets: state.enemyBullets.length,
      shotsFired: state.shotsFired,
      hordeEnemies: state.enemies.length,
      enemyTypes: [...new Set(state.enemies.map((enemy) => enemy.type))].sort().join(","),
      bosses: state.enemies.filter((enemy) => enemy.type === "boss").length,
      eliteEnemies: state.enemies.filter((enemy) => enemy.elite).length,
      eliteAffixes: [...new Set(state.enemies.filter((enemy) => enemy.elite).map((enemy) => enemy.affix))].sort().join(","),
      lootItems: (state.lootDrops || []).length,
      lootTypes: [...new Set((state.lootDrops || []).map((loot) => loot.type))].sort().join(","),
      shields: state.player.shields || 0,
      overdriveActive: (state.player.overdrive || 0) > 0,
      overdriveTime: Number((state.player.overdrive || 0).toFixed(2)),
      lootCores: state.player.lootCores || 0,
      relicChoices: state.relicChoices.length,
      relicCount: (state.player.relics || []).length,
      relicFields: (state.relicFields || []).length,
      relicSynergies: relicSynergies.map((synergy) => synergy.id).join(","),
      mountedWeapons: window.SurvivalRules.getMountedWeaponCount(state.player),
      plasmaBullets: state.bullets.filter((bullet) => bullet.style === "plasma").length,
      weaponEvolution: evolution.id,
      weaponSynergies: evolution.synergies.join(","),
      twinPlasmaBullets: state.bullets.filter((bullet) => bullet.style === "twinPlasma").length,
      piercingBullets: state.bullets.filter((bullet) => bullet.style === "piercingLaser").length,
      droneBullets: state.bullets.filter((bullet) => bullet.origin === "drone").length,
      coreDroneBullets: state.bullets.filter((bullet) => bullet.origin === "coreDrone").length,
      burningEnemies: state.enemies.filter((enemy) => (enemy.burnTime || 0) > 0).length,
      chainArcs: (state.chainArcs || []).length,
      sectorEvent: state.sector?.activeEvent?.type || "",
      threatLabel: state.spawnDirector?.lastDifficulty?.threatLabel || "",
      enemyCap: state.spawnDirector?.lastDifficulty?.enemyCap || 0,
      spawnInterval: state.spawnDirector?.lastDifficulty?.spawnInterval || 0,
      landmarkZone: state.landmarkState?.activeZone?.id || "",
      landmarks: state.landmarkState?.landmarks?.length || 0,
      landmarkRewardCharge: Number((state.landmarkState?.rewardCharge || 0).toFixed(2)),
      missionTitle: state.mission?.active?.title || "",
      missionProgress: state.mission?.active ? `${Math.floor(state.mission.active.progress)}/${state.mission.active.target}` : "",
      completedMissions: state.mission?.completed || 0,
      meteors: state.enemyBullets.filter((bullet) => bullet.style === "meteor").length,
      pierceRemaining: state.bullets.reduce((total, bullet) => total + (bullet.pierceLeft || 0), 0),
      upgradeChoices: state.upgradeChoices.length,
      upgradeCount: state.player.upgrades.length,
      spaceObjects: state.spaceObjects.length,
      starLayers: new Set(state.stars.map((star) => star.layer)).size,
    };
  }

  window.DalgaSavunmasiTest = {
    chooseUpgrade: window.DalgaSavunmasiGame.chooseUpgrade,
    endGame: window.DalgaSavunmasiGame.endGame,
    finishWave: window.DalgaSavunmasiGame.finishWave,
    forceBoss: window.DalgaSavunmasiGame.forceBoss,
    grantXp: window.DalgaSavunmasiGame.grantXp,
    hitFirstEnemy: window.DalgaSavunmasiGame.hitFirstEnemy,
    hitPlayer: window.DalgaSavunmasiGame.hitPlayer,
    snapshot: getSnapshot,
    start: window.DalgaSavunmasiGame.start,
    startPlaying: window.DalgaSavunmasiGame.startPlaying,
  };
})();
